image: clojure:latest

variables:
  POSTGRES_DB: sample-test
  DATABASE_URL: "postgresql://postgres@postgres:5432/sample-test"

services:
  - postgres:9.3

before_script:
  - lein deps

test: 
  before_script:
    - lein migratus migrate
  script: 
    - lein test

ancient:
  script:
    - lein ancient

