image: clojure:latest

variables:
  POSTGRES_DB: sample-test
  DATABASE_URL: "postgresql://postgres@postgres:5432/sample-test"

services:
  - postgres:9.3

stages:
  - test

test:
  stage: test
  script:
    - lein migratus migrate
    - lein test

ancient:
  stage: test
  script:
    - lein ancient
  allow_failure: true

kibit:
  stage: test
  script:
    - lein kibit